const components = {
  "Button": "Visual",
  "Card": "Visual",
  "Checkbox": "Visual",
  "Details": "Visual",
  "DropDown": "Visual",
  "Icon": "Visual",
  "imageCarousel": "Visual",
  "Input": "Visual",
  "Loading": "Visual",
  "Menu": "Visual",
  "Navbar": "Visual",
  "Select": "Visual",
  "Switch": "Visual",
  "ToastAlert": "Visual",
  "FetchManager": "Service",
  "IndexedDbManager": "Service",
  "LocalStorageManager": "Service",
  "Translator": "Service",
  "Controller": "Structural",
  "Debugger": "Structural",
  "Logger": "Structural",
  "StylesManager": "Structural"
}; export default components;