const components = {
  "Button": "Visual",
  "Card": "Visual",
  "Checkbox": "Visual",
  "CodeValidator": "Visual",
  "complexNavbar": "Visual",
  "Icon": "Visual",
  "imageCarousel": "Visual",
  "Information": "Visual",
  "Input": "Visual",
  "Loading": "Visual",
  "Menu": "Visual",
  "Navbar": "Visual",
  "Select": "Visual",
  "Switch": "Visual",
  "Tester": "Visual",
  "Tester2": "Visual",
  "ToastAlert": "Visual",
  "FetchManager": "Service",
  "IndexedDbManager": "Service",
  "LocalStorageManager": "Service",
  "Translator": "Service",
  "Controller": "Structural",
  "Debugger": "Structural",
  "Logger": "Structural",
  "StylesManager": "Structural"
}; export default components;