const components = {
  "HomePage": "AppComponents",
  "Playground": "AppComponents",
  "Button": "Visual",
  "Card": "Visual",
  "Checkbox": "Visual",
  "CodeVisualizer": "Visual",
  "Details": "Visual",
  "DropDown": "Visual",
  "Grid": "Visual",
  "Icon": "Visual",
  "Input": "Visual",
  "Layout": "Visual",
  "Loading": "Visual",
  "MultiRoute": "Visual",
  "Navbar": "Visual",
  "NotFound": "Visual",
  "Route": "Visual",
  "Link": "Visual",
  "Select": "Visual",
  "Switch": "Visual",
  "TreeItem": "Visual",
  "TreeView": "Visual",
  "FetchManager": "Service",
  "IndexedDbManager": "Service",
  "LocalStorageManager": "Service"
}; export default components;
